### ISSUE TITLE
Error loading: grafana-iot-twinmaker-sceneviewer-panel

### ISSUE THREAD

**Issue by binchoo** [grafana/grafana-iot-twinmaker-app#262] opened 2023-12-29 01:44 UTC
<img width="1509" alt="image" src="https://github.com/grafana/grafana-iot-twinmaker-app/assets/15683098/0c403c03-79a2-43fa-aaf6-de3b99046e96">

**What happened**:

1. Upgraded `grafana-iot-twinmaker-app` version to the lastest (1.10.1).
2. I now cannot see and edit the Scene Viewer panel. Other panels like Query Editor, Video Players and Alarm Configurations are not damaged.
3. My grafana displays "Error loading: grafana-iot-twinmaker-sceneviewer-panel" in a red box.

**What you expected to happen**:

I upgraded the plugin version as I'm announced that the Scene Viewer's AutoQuery feature is now available.

**How to reproduce it (as minimally and precisely as possible)**:

Upgrade the plugin version from `v1.6.3` to `1.10.1` and just try to use the Scene Viewer panel.
```
sudo grafana-cli plugins uninstall grafana-iot-twinmaker-app
sudo grafana-cli plugins install grafana-iot-twinmaker-app 1.10.1
sudo systemctl restart grafana-server
```

**Environment**: 
- amazon EC2 / amazon-linux-2
- Grafana version: Grafana v10.0.2
- Plugin version: 1.10.1

**Comment by fridgepoet** [comment] 2024-01-01 08:47
Hi @binchoo thanks for reporting this issue!
I was able to reproduce it locally on the Grafana version and Plugin version that you have reported.

Notes:
* I was able to git checkout the Grafana version v10.0.2 and Plugin version v1.10.1 and build locally and see the issue on the sample Alarm Dashboard.
* I was also able to checkout the Plugin version v1.10.1 and see the issue on Docker by running the following command from the `data/plugins` directory of Grafana (just because I used $PWD there, should be able to run it from anywhere with the absolute path): `docker run --rm  -p 3000:3000 --name=grafana --env GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-iot-twinmaker-app,grafana-iot-twinmaker-datasource,grafana-iot-twinmaker-alarm-configuration-panel,grafana-iot-twinmaker-layout-panel,grafana-iot-twinmaker-queryeditor-panel,grafana-iot-twinmaker-sceneviewer-panel --volume "$PWD/grafana-iot-twinmaker-app:/var/lib/grafana/plugins" grafana/grafana:10.0.2`
* Screenshot shows what I observe with the CookieFactory demo data

![Screenshot 2024-01-01 at 09 44 25](https://github.com/grafana/grafana-iot-twinmaker-app/assets/4163034/215ba32c-701a-4ead-9fbd-1550f26c2de3)

**Comment by mukeshsahay** [comment] 2024-01-02 19:48
Hi @binchoo, I verified this on the latest version of Grafana and the Scene Viewer panel is working fine.
This is a sample TwinMaker dashboard on play.grafana and Scene Viewer is working fine - https://play.grafana.org/d/y1FGfj57z/aws-iot-twinmaker-mixer-alarm-dashboard?orgId=1

Will it be possible for you to upgrade the Grafana version and see if that fixes this issue for you?

**Comment by binchoo** [comment] 2024-01-03 02:21
Hey @mukeshsahay, thanks for your suggestion. 

I'm now using the latest versions of Grafana and `grafana-iot-twinmaker-app` plugin, and seeing them working fine. 
I also verified the AutoQuery feature could automatically collect data streams.

<img width="1501" alt="image" src="https://github.com/grafana/grafana-iot-twinmaker-app/assets/15683098/b8e4b779-aa69-42fa-b6d2-0187786daf95">

I guess this issue can be closed, if no further improvement is planned.

**Comment by idastambuk** [comment] 2024-01-03 15:29
Hi @binchoo great to know it's working for you, thanks for letting us know! Will close this then

**Closed by idastambuk** 2024-01-03 15:29 UTC
Labels: type/bug, datasource/TwinMaker

**Comment by binchoo** [comment] 2024-01-07 06:15
Will a documentation notice that Grafana_v10.0.2 is not compatible with the plugin? Just because this may bother some users.
